name: Review code
description: Learning a review action
author: Zoarisoa Voahary Mampionona

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  github_token:
    description: Github Secret token
    required: true

runs:
  using: node20
  main: dist/index.js
